# Site settings
title: Dhruv Singh
description: 'Self taught programmer, working on Python and Django'
url: 'http://dhruvsingh.github.io'
baseurl: '/'
google_analytics: 'UA-32861100-9'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Dhruv Singh'
  email: dhruvsingh.er@gmail.com
  twitter_username: _dhruvsingh
  facebook_username: sudo.dhruv
  github_username:  dhruvsingh
  linkedin_username:  fuzzylogic

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 3
permalink: /:month/:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
